### ISSUE TITLE
Add config.xml configuration for cordova-plugin-whitelist

### ISSUE THREAD

**Issue by rozele** [CatalystCode/cordova-plugin-cogsvcsspeech#23]
In the Cognitive Services plugin code, we take a dependency on cordova-plugin-whitelist. Curious what the purpose of that dependency is.

**Comment by bsherwin** [comment]
This was most likely added by the Cordova template and we just haven't got to locking the app down yet, but it is recommended practice... [Cordova whitelist and Content Security Policy guide](https://docs.microsoft.com/en-us/visualstudio/cross-platform/tools-for-cordova/security/whitelists?view=toolsforcordova-2017)

**Comment by esgraham** [comment]
Closing issue as it is recommended practice.
