### ISSUE TITLE
Request Permission

### ISSUE THREAD

**Issue by esgraham** [CatalystCode/cordova-plugin-cogsvcsspeech#3]
## Description 
As an architect, I want to determine if the plugin needs to request permissions or require that the calling application handle the permission request.

## Acceptance Criteria
- Review other Cordova plugins to determine if the plugin handles required permissions.  Be sure to include plugins that use the microphone and speakers of the phones.
- Create a chart that details and how many plugins handle the permissions vs leaving the functionality in the calling application
- Update README to detail the findings and determine the functionality for the plugin.

**Comment by bsherwin** [comment]
Looking at a few other plugins (notable ones linked here) it appears that the standard approach is that the Cordova plugin does its own permission check.
[See Apache Media Plugin](https://github.com/apache/cordova-plugin-media/blob/acffc0c7b16856e888c932628750fc8b29f1db3d/src/android/AudioHandler.java#L93)
[See Apache Camera Plugin](https://github.com/apache/cordova-plugin-camera/blob/6feaa95559f384468286ab28070030887bac1c5d/src/android/CameraLauncher.java#L194)
[See DBMeter](https://github.com/akofman/cordova-plugin-dbmeter/blob/46725cd9571f291a94a0a40ed705ce65b96598d1/plugin/src/android/DBMeter.java#L39)

**Comment by esgraham** [comment]
Add Permission Request to iOS code.
